### ISSUE TITLE
Errors when attempting to build a module 

### ISSUE THREAD

**Issue by mambax7** [txmodxoops/TDMCreate-1.91#10]
I very much appreciate your efforts to develop this module, but as we've talked about it before, you need to improve your testing. 
Have you installed it as a new module and tested it?  It's possible that it was working on your installation that you had, but it's important that you install it fresh on another XOOPS installation and test it there. 
And think "Codeception" :)

![image](https://cloud.githubusercontent.com/assets/613686/7787445/658e2326-01da-11e5-9890-8613fb23684a.png)

**Comment by txmodxoops** [comment]
Put this on _construct of UserRss.php
parent::__construct();
$this->tdmcfile = TDMCreateFile::getInstance();
$this->userobjects = UserObjects::getInstance();

I think I need a hand:
D:\UwAmp\www\xoops-2.5.7testTDMCreate1.91\xoops_lib> 
./vendor/bin/codecept run
Codeception PHP Testing Framework v2.0.13
Powered by PHPUnit 4.6.6 by Sebastian Bergmann and contributors.

## Acceptance Tests (0) ------------------------

## Functional Tests (0) ------------------------

## Unit Tests (0) ------------------------------

Time: 2.31 seconds, Memory: 7.75Mb
No tests executed!
PS D:\UwAmp\www\xoops-2.5.7testTDMCreate1.91\xoops_lib>

**Comment by txmodxoops** [comment]
There is a problem that I can not understand!

When I create a new module, and I click the link Go to module nothing happens

**Comment by txmodxoops** [comment]
Sample test with Codeception:

PS D:\UwAmp\www\xoops-2.5.7testTDMCreate1.91\xoops_lib> ./vendor/bin/codecept run
Codeception PHP Testing Framework v2.0.13
Powered by PHPUnit 4.6.6 by Sebastian Bergmann and contributors.

## Acceptance Tests (1) ---------------------------------------------------------------------------------

Perform actions and see result (TDMCreateCept)

##                 Ok

---

## Functional Tests (0) ------------------------

## Unit Tests (0) ------------------------------

Time: 2.06 seconds, Memory: 9.25Mb

OK (1 test, 1 assertion)
PS D:\UwAmp\www\xoops-2.5.7testTDMCreate1.91\xoops_lib> ./vendor/bin/codecept run acceptance --steps
Codeception PHP Testing Framework v2.0.13
Powered by PHPUnit 4.6.6 by Sebastian Bergmann and contributors.

## Acceptance Tests (1) ---------------------------------------------------------------------------------

Perform actions and see result (TDMCreateCept)
Scenario:
- I am on page "http://localhost/xoops-2.5.7testTDMCreate1.91/htdocs/modules/profile/register.php"
- I see "user"
  PASSED

---

---

Time: 1.1 seconds, Memory: 9.25Mb

OK (1 test, 1 assertion)
PS D:\UwAmp\www\xoops-2.5.7testTDMCreate1.91\xoops_lib>

I hope hunderstand! --performance

**Comment by txmodxoops** [comment]
Fixed bugs

**Comment by mambax7** [comment]
OK, your changes fixed the "building" issue.
However,  I cannot install the module:

> Unable to install zmodule. 
> Error(s):Installing ZModule
> Invalid default value for 'parent'

This is what it is generating: 

>  `parent` TINYINT(8)  DEFAULT '',

while it should be this:

>   `parent` TINYINT(8)  DEFAULT '0',

![image](https://cloud.githubusercontent.com/assets/613686/7790262/6ec87a7a-024f-11e5-8791-ac029eeec9bc.png)

**Comment by txmodxoops** [comment]
Ok!

I've solved with this code line in SqlFile.php

case 2:
                    case 3:
                    case 4:
                    case 5:
                    case 6:
                    case 7:
                    case 8:
                        if(empty($fieldDefault)) {
                            $default = "DEFAULT '0'";
                        } else {
                            $default = "DEFAULT '{$fieldDefault}'";
                        }
                        break;

if the default field is empty, automatically write 0 in database fields

**Comment by mambax7** [comment]
Thanks! I'll test it later

**Comment by txmodxoops** [comment]
Download all from release 2 5 that have others addons

**Comment by txmodxoops** [comment]
Released https://github.com/txmodxoops/TDMCreate-1.91/releases/tag/alpha-3

**Comment by mambax7** [comment]
![image](https://cloud.githubusercontent.com/assets/613686/7941991/f14e6448-0928-11e5-9706-2adf78a258c6.png)

**Comment by txmodxoops** [comment]
Please tell me which items you used in fields elements?

From the pictures you see me everything works well

![test1_tdmcreate_categories_list](https://cloud.githubusercontent.com/assets/539148/7953222/6fa9ae76-09c2-11e5-94b5-8d193b295c10.gif)

![test1_tdmcreate_downloads_form](https://cloud.githubusercontent.com/assets/539148/7953223/78632830-09c2-11e5-9783-1762ed7f2e99.gif)

![test1_tdmcreate_downloads_list](https://cloud.githubusercontent.com/assets/539148/7953227/8206439a-09c2-11e5-8e18-abbe446a052d.gif)

![test1_tdmcreate_index](https://cloud.githubusercontent.com/assets/539148/7953231/8e04aa10-09c2-11e5-9755-322717ab024f.gif)

**Comment by mambax7** [comment]
The lack of testing is killing me :(
I install the latest release, and when I try to open it, I am getting this:
![image](https://cloud.githubusercontent.com/assets/613686/7957905/c046ca26-09b8-11e5-896a-3b8b0428002e.png)

You need to run a fresh installation before releasing it. Or run Codeception tests after each change that you make to the code. 
Please invest the time into testing tools like Codeception and make it a part of your release process. This will make your life (and ours) much easier over time :)

**Comment by txmodxoops** [comment]
Fixed now

Just now I'm learn Codeception :100:

**Comment by mambax7** [comment]
:+1:
