### ISSUE TITLE
include/common.php

### ISSUE THREAD

**Issue by ggoffy** [txmodxoops/TDMCreate-1.91#109]
Hi 

an example of a module I created with tdmcreate:
`if (!defined('WGXPIWIK_MODULE_PATH')) {
    define('XOOPS_ICONS32_PATH', XOOPS_ROOT_PATH . '/Frameworks/moduleclasses/icons/32');
    define('XOOPS_ICONS32_URL', XOOPS_URL . '/Frameworks/moduleclasses/icons/32');
    define('WGXPIWIK_DIRNAME', 'wgxpiwik');
    define('WGXPIWIK_PATH', XOOPS_ROOT_PATH.'/modules/'.WGXPIWIK_DIRNAME);
    define('WGXPIWIK_URL', XOOPS_URL.'/modules/'.WGXPIWIK_DIRNAME);
    define('WGXPIWIK_ICONS_PATH', WGXPIWIK_PATH.'/assets/icons');
    define('WGXPIWIK_ICONS_URL', WGXPIWIK_URL.'/assets/icons');
    define('WGXPIWIK_IMAGE_PATH', WGXPIWIK_PATH.'/assets/images');
    define('WGXPIWIK_IMAGE_URL', WGXPIWIK_URL.'/assets/images');
    define('WGXPIWIK_UPLOAD_PATH', XOOPS_UPLOAD_PATH.'/'.WGXPIWIK_DIRNAME);
    define('WGXPIWIK_UPLOAD_URL', XOOPS_UPLOAD_URL.'/'.WGXPIWIK_DIRNAME);
    define('WGXPIWIK_ADMIN', WGXPIWIK_URL . '/admin/index.php');
    $local_logo = WGXPIWIK_IMAGE_URL . '/wedega.png';
    define('WGXPIWIK_PIWIK_CONFIG_INI', WGXPIWIK_PATH.'/piwik/config/config.ini.php');

}`

now two questions:
1) WGXPIWIK_MODULE_PATH will not be define within the if-condition, so this if-block will always be executed
a) we can remove the condition, or
b) we use in the condition a defined var (eg. WGXPIWIK_PATH instead of WGXPIWIK_MODULE_PATH

2) if you have more than one module created by tdmcreate, you get the notice "Constant XOOPS_ICONS32_PATH already defined....
we should use 
`if (!defined('XOOPS_ICONS32_PATH')) define('XOOPS_ICONS32_PATH', XOOPS_ROOT_PATH . '/Frameworks/moduleclasses/icons/32');
    if (!defined('XOOPS_ICONS32_URL')) define('XOOPS_ICONS32_URL', XOOPS_URL . '/Frameworks/moduleclasses/icons/32');`

**Comment by ggoffy** [comment]
in which way I should make the changes?

**Comment by txmodxoops** [comment]
I believe that the solution a) is the best for the moment

The "Constant XOOPS_ICONS32_PATH" It should be only once in include/common.php

**Comment by ggoffy** [comment]
done
