### ISSUE TITLE
Wrong link to forum support

### ISSUE THREAD

**Issue by cesagonchu** [txmodxoops/TDMCreate-1.91#124]
Wrong link to forum support

tdmcreate/templates/admin/tdmcreate_footer.tpl
line 6

replace:

`<a href='http://xoops.org/forums/newbb' title='Visit Support Forum' class='tooltip' rel='external'>Support Forum</a></div>`

with:

`<a href='http://xoops.org/modules/newbb/' title='Visit Support Forum' class='tooltip' rel='external'>Support Forum</a></div>`

Thanks! :-)

**Comment by txmodxoops** [comment]
Thanks Cesag!

I entered a default text field, for each module in preferences.
