### ISSUE TITLE
missing define to be added

### ISSUE THREAD

**Issue by cesagonchu** [txmodxoops/TDMCreate-1.91#125]
There are 3 missing define:

![tdmcreatecorrecfr](https://cloud.githubusercontent.com/assets/4613970/15180008/60968d0c-177f-11e6-8e0d-42639258afa3.gif)

1 - Donation Amount

tdmcreate/include/functions.php
Line 116 and line 123
## 

2 - is maintained by the

tdmcreate/template/admin/tdmcreate_footer.tpl
Line 5:
`<strong><{$module_name}></strong> is maintained by the`
## 

3 - Support Forum

tdmcreate/template/admin/tdmcreate_footer.tpl
Line 6:
`<a href='http://xoops.org/forums/newbb' title='Visit Support Forum' class='tooltip' rel='external'>Support Forum</a></div>`

**Comment by txmodxoops** [comment]
Send a PR

**Comment by cesagonchu** [comment]
I'm not a programmer. I prefer you do it.

**Comment by txmodxoops** [comment]
Ok!

Thanks
