### ISSUE TITLE
templates system_bookmarks.tpl and system_fbcomments.tpl

### ISSUE THREAD

**Issue by ggoffy** [txmodxoops/TDMCreate-1.91#135]
Hi

If I create a new module, the templates system_bookmarks.tpl and system_fbcomments.tpl will be implemented in ..._footer.tpl by
```
<{if $bookmarks != 0}>
<{include file="db:system_bookmarks.html"}>
<{/if}>

<{if $fbcomments != 0}>
<{include file="db:system_fbcomments.html"}>
<{/if}>
```
but normally in the current xoops core system these templates are not available.

How to solve?

**Comment by txmodxoops** [comment]
I believe there is included in source forge in the repository of old versions, try to check them

**Comment by ggoffy** [comment]
hi

old version of tdmcreate or old xoops version?

But: In my opinion there are only two ways to solve this:
1) add these files to current xoops core
or
2) remove these options in the module creation procedure of tdmcreate

what do you think?

**Comment by txmodxoops** [comment]
Old version of tdmcreate

**Comment by ggoffy** [comment]
I looked on sourceforge, but I couldn't find something.

But if it is a relict from old versions and not included in current xoops core system, then it should be remove also from creation procedure in tdmcreate.

I will remove this from my modules.

**Comment by txmodxoops** [comment]
where's your fork?

**Comment by ggoffy** [comment]
if you mean tdmcreate: from this module I have currently no fork.

my module with this code was wgtimelines, but I have removed already this part/options

**Comment by ggoffy** [comment]
I remove it from tdmcreate
