### ISSUE TITLE
Fatal error: Class 'TDMCreateFormTabTray' 

### ISSUE THREAD

**Issue by mambax7** [txmodxoops/TDMCreate-1.91#14]
![image](https://cloud.githubusercontent.com/assets/613686/8103220/bd5c7864-0ff4-11e5-90f5-94d249973b6a.png)

**Comment by txmodxoops** [comment]
I don't understand! 
Look at the images in both XOOPS 2.5.7 and 2.5.8

![settings_tdmcreate_xoops257](https://cloud.githubusercontent.com/assets/539148/8105554/7b048290-103a-11e5-98d3-73b918a49fc5.GIF)

![settings_tdmcreate_xoops258](https://cloud.githubusercontent.com/assets/539148/8105557/859aa14e-103a-11e5-9559-067ef7d0362d.GIF)

Try to manually clear the cache of classes.

**Comment by mambax7** [comment]
Clearing cache helped, but I should NOT have to clear the cache manually, because you keep uploading YOUR  personal cache file to GitHub :(
Please make sure that you don't upload this file, or if you keep forgetting it, please move the cache to the standard XOOPS cache directory, so it's not part of the TDMCreate module. 
This cannot be part of source code:
https://github.com/txmodxoops/TDMCreate-1.91/blob/master/class/cache/classpaths.cache

**Comment by txmodxoops** [comment]
You're right!

I am quiet for this because when creating the file with the build, as you can see in the file admin/building.php cache files are deleted first and then again re-created automatically.

Unfortunately I had not thought of doing this for the external folder, now I change the path :+1:
