### ISSUE TITLE
getConfig() error

### ISSUE THREAD

**Issue by myxoops** [txmodxoops/TDMCreate-1.91#141]
Hi,
I have created one table as category and one is standard.
With the category everything works fine. When I try to create a item in the second table i get following error 
Notice: Undefined variable: countdown in file /modules/module1/admin/footer.php line 24
Error: Error: Call to a member function getConfig() on null in file /modules/module1/admin/footer.php line 24
This occurs after you create the first item. 

I am using xoops 2.5.9

**Comment by myxoops** [comment]
Opening the module on the userside is also not working 
there are errors like:
Notice: Undefined variable: countdown in file /modules/module1/index.php line 64
Error: Error: Call to a member function getConfig() on null in file /modules/module1/index.php line 64

The line is: 
module1MetaKeywords($module1->getConfig('keywords').', '. implode(',', $keywords));

**Comment by ggoffy** [comment]
hi

did you use the current version from github?

i have testet once more. my module name for testing was 'testtdmcreate'
the equal line in my index.php is
`testtdmcreateMetaKeywords($testtdmcreate->getConfig('keywords').', '. implode(',', $keywords));`

if your module name is "module1" the line should be
`module1MetaKeywords($module1->getConfig('keywords').', '. implode(',', $keywords));`

can you please change your line to this and test.

I have no idea why there is '...($countdown->getConfig...'

**Comment by myxoops** [comment]
I have downloaded it from here 
https://github.com/txmodxoops/tdmcreate 

I have changed the name of the modules in this posted lines. So the module name is 100% correct. 
Today I have tested it again with different names of the module and I still get the same error. 

It is a really easy module. 2 tables and one of them is a category.

**Comment by myxoops** [comment]
Ok I just checked it on my second system and there it works perfect. 
Maybe there is a problem with different PHP versions. I will check it

**Comment by ggoffy** [comment]
yes, thank you. please let me know the result
