### ISSUE TITLE
Tabs used in source

### ISSUE THREAD

**Issue by mambax7** [txmodxoops/TDMCreate-1.91#15]
Please do not use tabs in source code.  We need to follow  PSR-2 code style

Run you code through CS-Fixer before you upload it to GitHub:
https://github.com/FriendsOfPHP/PHP-CS-Fixer

**Comment by txmodxoops** [comment]
you're referring to this?

![tabs_settings](https://cloud.githubusercontent.com/assets/539148/8283645/ba2ed56c-18f8-11e5-9cb6-2acb82d109cb.GIF)

**Comment by txmodxoops** [comment]
PS D:\UwAmp\www\xoops-2.5.7testTDMCreate1.91\htdocs> php .\php-cs-fixer.phar fix .\modules\tdmcreate\class
   1) files\language\LanguageAdmin.php
   2) files\language\LanguageBlocks.php
   3) files\language\LanguageDefines.php
   4) files\language\LanguageHelp.php
   5) files\language\LanguageMailTpl.php
   6) files\language\LanguageMain.php
   7) files\language\LanguageModinfo.php
   8) files\sql\SqlFile.php
   9) files\TDMCreateAbstract.php
  10) files\TDMCreateArchitecture.php
  11) files\TDMCreateFile.php
  12) files\TDMCreateHtmlSmartyCodes.php
  13) files\TDMCreateMoreFiles.php
  14) files\TDMCreateStructure.php
  15) files\TDMCreateTableFields.php
  16) files\templates\admin\TemplatesAdminAbout.php
  17) files\templates\admin\TemplatesAdminFooter.php
  18) files\templates\admin\TemplatesAdminHeader.php
  19) files\templates\admin\TemplatesAdminIndex.php
  20) files\templates\admin\TemplatesAdminPages.php
  21) files\templates\admin\TemplatesAdminPermissions.php
  22) files\templates\blocks\TemplatesBlocks.php
  23) files\templates\user\TemplatesUserBreadcrumbs.php
  24) files\templates\user\TemplatesUserBroken.php
  25) files\templates\user\TemplatesUserCategories.php
  26) files\templates\user\TemplatesUserCategoriesList.php
  27) files\templates\user\TemplatesUserDisqusComments.php
  28) files\templates\user\TemplatesUserFacebookComments.php
  29) files\templates\user\TemplatesUserFooter.php
  30) files\templates\user\TemplatesUserHeader.php
  31) files\templates\user\TemplatesUserIndex.php
  32) files\templates\user\TemplatesUserPages.php
  33) files\templates\user\TemplatesUserPagesList.php
  34) files\templates\user\TemplatesUserPdf.php
  35) files\templates\user\TemplatesUserPrint.php
  36) files\templates\user\TemplatesUserRate.php
  37) files\templates\user\TemplatesUserRss.php
  38) files\templates\user\TemplatesUserSearch.php
  39) files\templates\user\TemplatesUserSingle.php
  40) files\templates\user\TemplatesUserSubmit.php
  41) files\user\UserBroken.php
  42) files\user\UserFooter.php
  43) files\user\UserHeader.php
  44) files\user\UserIndex.php
  45) files\user\UserListTag.php
  46) files\user\UserNotificationUpdate.php
  47) files\user\UserObjects.php
  48) files\user\UserPages.php
  49) files\user\UserPdf.php
  50) files\user\UserPrint.php
  51) files\user\UserRate.php
  52) files\user\UserRss.php
  53) files\user\UserSearch.php
  54) files\user\UserSingle.php
  55) files\user\UserSubmit.php
  56) files\user\UserViewTag.php
  57) files\user\UserVisit.php
  58) files\user\UserXoopsVersion.php
  59) form\TDMCreateFormRadio.php
  60) form\TDMCreateFormRaw.php
  61) form\TDMCreateFormTab.php
  62) form\TDMCreateFormTabTray.php
  63) form\TDMCreateThemeForm.php
  64) helper.php
  65) html\TDMCreateFormLabel.php
  66) logoGenerator.php
  67) modules.php
  68) morefiles.php
  69) session.php
  70) settings.php
  71) splclassloader.php
  72) tables.php
Fixed all files in 116.323 seconds, 11.500 MB memory used

**Comment by txmodxoops** [comment]
Deleted tabs tray
