### ISSUE TITLE
Bugs in generated templates for tables

### ISSUE THREAD

**Issue by mambax7** [txmodxoops/TDMCreate-1.91#16]
For table news the code generated in: /mymodule/templates/mymodule_news.tpl
line 11: <{foreach item= from=$news}>
line 14: <{include file="db:zumba_news_list.tpl" list=$}>
line 17:  <{if $.count eq $divideby}>

![image](https://cloud.githubusercontent.com/assets/613686/8147262/ccbd1b96-122f-11e5-979b-bf068c0d9896.png)

**Comment by txmodxoops** [comment]
Unfortunately errors are caused by native code to be reviewed.

If don't use table_fieldname, this cause issues

Future versions will use the classes that will certainly be better and less duplicate methods :1234:
