### ISSUE TITLE
wrong code generated for class

### ISSUE THREAD

**Issue by mambax7** [txmodxoops/TDMCreate-1.91#2]
![image](https://cloud.githubusercontent.com/assets/613686/7384769/5e24446c-ee07-11e4-8a8d-206fb8d3d209.png)

During code generation, the value of $ucfTableFieldname is missing here:
public function get{$ucfTableFieldname}FromId(\${$tableFieldname}Id) 

so you're getting this:

![image](https://cloud.githubusercontent.com/assets/613686/7384794/da474954-ee07-11e4-98e0-9ffe30079c9b.png)

Also, please replace intval() with (int)

**Comment by txmodxoops** [comment]
Pleace Michael!

change in admin/fields.php?op=save the functions !empty() with isset()

Il 29/04/2015 06:39, Mamba (Michael Beck) ha scritto:

**Comment by txmodxoops** [comment]
You have omitted field table_fieldname in admin/tables.php, but I have a solution for this

**Comment by txmodxoops** [comment]
Solved
