### ISSUE TITLE
Missing names for variables

### ISSUE THREAD

**Issue by mambax7** [txmodxoops/TDMCreate-1.91#31]
It seems like that when I don't use prefixes for tables, you're missing names in the variables:

C:\wamp64\www\257tdmc191\modules\zumba3\print.php
![image](https://cloud.githubusercontent.com/assets/613686/8422992/b040651c-1eb0-11e5-88e3-c7376e6b20c5.png)

C:\wamp64\www\257tdmc191\modules\zumba3\index.php

![image](https://cloud.githubusercontent.com/assets/613686/8423007/e2ede53e-1eb0-11e5-9cb2-0260e2655161.png)

**Comment by mambax7** [comment]
The issue still exist, if you leave empty the field name prefix:
![image](https://cloud.githubusercontent.com/assets/613686/14833432/44c2abfa-0bcd-11e6-87c3-180ece5e54bc.png)

**Comment by mambax7** [comment]
This is what is going on:
1) You have this function:

``` php
    public function getXcGetValues($tableName, $tableSoleName, $index = 'i', $noArray = false, $t = '')
    {
        $index = '' !== $index ? $index: 'i';
        $ucfTableName = ucfirst($tableName);
        if (!$noArray) {
            $ret = "{$t}\${$tableSoleName} = \${$tableName}All[\${$index}]->getValues{$ucfTableName}();\n";
        } else {
            $ret = "{$t}\${$tableSoleName} = \${$tableName}->getValues{$ucfTableName}();\n";
        }

        return $ret;
    }
```

When you call it from inside the function getBodyCategoriesIndex, you call it as:

``` php
$foreach = $this->xc->getXcGetValues($tableName, $tableSoleName, $tableFieldname, false, "\t");
```

Since the  $tableFieldname is empty, the $index remains empty, because the default that you set as index = 'i' will never be set, as PHP will see the '' as valid. 

So you need to add a check:

``` php
$index = '' !== $index? $index: 'i';
```

2) You are sending the wrong variable in the function getBodyPagesIndex.

The function expects " $tableSoleName":

``` php
function getXcGetValues($tableName, $tableSoleName, $index = 'i', $noArray = false, $t = '')
```

but you're sending "$tableFieldname" which is empty

``` php
$foreach = $this->xc->getXcGetValues($tableName, $tableFieldname, 'i', false, "\t");
```

so the generated code for a table "news" is then:

``` php
    foreach(array_keys($newsAll) as $) {
        $ = $newsAll[$i]->getValuesNews();
```

instead of:

``` php
    foreach(array_keys($newsAll) as $i) {
        $news = $newsAll[$i]->getValuesNews();
```

**Comment by txmodxoops** [comment]
Merged!
