### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by mambax7** [txmodxoops/TDMCreate-1.91#36]
I just tried to generate a module with the latest version from GitHub, but got bunch of errors (see below). 

One of the issues was that TDMCreate generated this line  in /admin/index.php:

```
include header .'/.php';
```

( ! ) Notice: Use of undefined constant header - assumed 'header' in C:\wamp64\www\257tdmc191\modules\zumba5\admin\index.php on line 22
Call Stack
# Time    Memory  Function    Location

1   0.0004  275528  {main}( )   ...\index.php:0

( ! ) Warning: include(header/.php): failed to open stream: No such file or directory in C:\wamp64\www\257tdmc191\modules\zumba5\admin\index.php on line 22
Call Stack
# Time    Memory  Function    Location

1   0.0004  275528  {main}( )   ...\index.php:0

( ! ) Warning: include(): Failed opening 'header/.php' for inclusion (include_path='.;c:\php\includes;C:\wamp64\www\zend1\library\Zend;C:\wamp64\www\symfony1\lib;C:\wamp64\www\symfony1\data\bin') in C:\wamp64\www\257tdmc191\modules\zumba5\admin\index.php on line 22
Call Stack
# Time    Memory  Function    Location

1   0.0004  275528  {main}( )   ...\index.php:0

( ! ) Notice: Undefined variable: topicsHandler in C:\wamp64\www\257tdmc191\modules\zumba5\admin\index.php on line 25
Call Stack
# Time    Memory  Function    Location

1   0.0004  275528  {main}( )   ...\index.php:0

( ! ) Fatal error: Call to a member function getCount() on null in C:\wamp64\www\257tdmc191\modules\zumba5\admin\index.php on line 25
Call Stack
# Time    Memory  Function    Location

1   0.0004  275528  {main}( )   ...\index.php:0

**Comment by txmodxoops** [comment]
Because a lot of duplicate code, I created a single function that includes both calls include, include_once that is why I did not realize you need to change even those who had already written in some file.

Fixed! :+1:
