### ISSUE TITLE
editorHandler in xoops_version.php

### ISSUE THREAD

**Issue by mambax7** [txmodxoops/TDMCreate-1.91#62]
![image](https://cloud.githubusercontent.com/assets/613686/12869564/81c3dd46-ccf1-11e5-9e43-7f7302f7effb.png)

`// Editor Array
xoops_load('xoopseditorhandler');
editorHandler = XoopsEditorHandler::getInstance();`

The '$' is missing for 'editorHandler'

**Comment by txmodxoops** [comment]
Scrutinizer It giving me a lot of information about the code and what I'm changing a lot of things.

I'm doing some tests but I get no such error, likely to be a function which is not used in my tests.

I will immediately correct the error

**Comment by txmodxoops** [comment]
Fixes
