### ISSUE TITLE
Permissions are not saved 

### ISSUE THREAD

**Issue by mambax7** [txmodxoops/TDMCreate-1.91#64]
![image](https://cloud.githubusercontent.com/assets/613686/12869745/1089c780-ccf6-11e5-9b32-3bb9d5cf23d6.png)

I set permissions, save them, receive a message that they are saved, but when I open it again, the permissions are empty again.

**Comment by txmodxoops** [comment]
I'm not using any categories but regular table, it works well, I will easily with the categories.

I also want to create a code that can use the permissions for any file

**Comment by txmodxoops** [comment]
Because the table that you have inherited is not in the file permissions.php

**Comment by txmodxoops** [comment]
But it is strange, I see that it works on one and not the other

![tdmc_test_category_perm](https://cloud.githubusercontent.com/assets/539148/12870042/1f89d266-cd32-11e5-96fe-a357aed03b01.png)

![tdmc_test_one_perm1](https://cloud.githubusercontent.com/assets/539148/12870048/2d25b264-cd32-11e5-9eec-1b07351f1d4c.png)

![tdmc_test_one_perm](https://cloud.githubusercontent.com/assets/539148/12870043/2554adb0-cd32-11e5-9b23-8c0e9ea49e9a.png)

**Comment by txmodxoops** [comment]
I was able in part to fix

I could not understand why, you can change from global permissions, but not by the individual categories

**Comment by ggoffy** [comment]
solved in last version
