### ISSUE TITLE
delete code in admin pages

### ISSUE THREAD

**Issue by ggoffy** [txmodxoops/TDMCreate-1.91#77]
when creating the php code of admin pages function getXoopsCodeCaseDelete is used instead of function getAdminPhpCodeDelete

getXoopsCodeCaseDelete has errors inside
getAdminPhpCodeDelete has no errors

**Comment by txmodxoops** [comment]
You can fix this & send me a pull request? Thanks

**Comment by txmodxoops** [comment]
Sorry!

The file AdminPhpCode & AdminObjects will be eliminated, instead of this is created  AdminXoopsCode

**Comment by ggoffy** [comment]
sorry, but in AdminXoopsCode.php there is no code for creating the delete-code-block in the admin pages
I do not know, how to solve

**Comment by txmodxoops** [comment]
Take getXoopsCodeCaseDelete function and enter it in AdminXoopsCode
Renamed AdminXoopsCodeCaseDelete
You will receive the error, but you will understand that they are logical errors because of links to the class, outside now, TDMCreateXoopsCode

**Comment by ggoffy** [comment]
do you mean an error like this:
Fatal error: Call to a member function getCamelCase() on a non-object in C:\Homepages\Xampp\htdocs\wgbacklinks\htdocs\modules\tdmcreate\class\files\admin\AdminXoopsCode.php on line 331
and now?

if you want, I can clean up the bugs in getXoopsCodeCaseDelete. you can put it then where you want

**Comment by txmodxoops** [comment]
I sent the changes right now, I did some testing I do not receive any error.

download new files

**Comment by ggoffy** [comment]
yes, no error, but also no files for my tables in folder admin :-(

**Comment by txmodxoops** [comment]
Get the last commit
